version: '3.4'

services:
  sql.data:
      environment:
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
      ports:
        - "5433:1433"

  tailwindtraders.rewards.website:
    environment:
    - dbContext=Server=sql.data;Database=rewardsdb;User Id=sa;Password=Pass@word
    ports:
      - "2100:80"

# networks:
#   default:
#     external:
#       name: nat
